project:
  type: website
  resources:
    - "KNN/Introdução.mp4"
    - "KNN/KNN - Criando o Modelo.mp4"

website:
  title: "Objetos de Aprendizagem"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Início"
        file: index.md
      - section: "Modelos de Machine Learning"
        contents:
          - text: "Modelo K-NN"
            file: "KNN/K-NN-EN.ipynb"

format:
  html:
    theme: cosmo
    toc: true
