project:
  type: website
  resources:
    - "KNN/Introdução.mp4" # Se tiver mais vídeos, basta ir adicionando linhas com "- pasta/nome.mp4" aqui embaixo

website:
  title: "Objetos de Aprendizagem"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Início"
        file: index.md
      - section: "Modelos de Machine Learning"
        contents:
          - KNN/K-NN-EN.ipynb

format:
  html:
    theme: cosmo
    toc: true
