project:
  type: website

website:
  title: "Objetos de Aprendizagem"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Início"
        file: README.md
      - section: "Modelos de Machine Learning"
        contents:
          - KNN/K-NN-EN.ipynb.ipynb

format:
  html:
    theme: cosmo
    toc: true
